autoware:
  root: "/opt/autoware"
  ros_setup_script: "/opt/ros/humble/setup.bash"

  launch:
    package: "autoware_launch"
    file: "sbsvf.launch.xml"
    headless: false
    log_path: "/tmp/autoware_launch.log"
    # extra_args:
    # - "launch_rviz:=false"
    # - "launch_system_monitor:=false"
    # - "launch_perception:=true"

  data:
    map_base_path: "/autoware_map"
    default_map_subdir: "sample-map-planning"
    data_path: "/autoware_data"

  vehicle:
    model: "sample_vehicle"
    sensor_model: "sample_sensor_kit"

  runtime:
    timeout_sec: 10.0
    control_timeout_sec: 0.1
    spin_rate_hz: 100.0
    allow_goal_modification: false
    # publish_objects: true
    # use_dynamic_objects_topic: true
